### ISSUE TITLE
How can this driver be used to setup W150S1 on an Android ROM?

### ISSUE THREAD

**Issue by veryraregaming** [CoreELEC/w1-aml#1]
My Android Tv Box has this wifi but i cannot get a 64bit OS working with wifi, any help would be appreciated

**Comment by Portisch** [comment]
You will need whole Android sources to be able to compile the driver into it

**Comment by veryraregaming** [comment]
Thank you so much for your response, I’ve seen your name quite a bit while searching for this driver, I have looked online and cannot find any S905W Roms with this Wi-Fi, I have found a 32bit but need 64, is this something that is very complex as if it’s the only way then I will have to learn and build a basic rom which can be rooted, pass safety net and have working Wi-Fi. I do not need anything in addition to this.
